name = "Industrial Civilization Survival"
author = "xenodeve"
version = "0.2.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d304d8cb8485addaa86ea0d4311ec4fed3936f67aa6be79040aa5571c2aded6b"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
