name = "Industrial Civilization Survival"
author = "xenodeve"
version = "0.2.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b94ff2060134651f662562625f08bdcff84d3f84a4ca5f6bc5d92c87f4e549d6"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
