#!/usr/bin/env node
// Merge everything captured in one session into one report.
//
//   node scripts/analyze/session-report.mjs \
//     --log "<instance>/logs/latest.log" \
//     --spark <code-or-json>            (repeatable) \
//     --capframex capture.csv \
//     --profiler profiling-result.txt \
//     [--expect-gpu "RTX 4070 SUPER"] [--out report.md]
//
// WHY THIS EXISTS. Each tool answers a different question and none of them is
// complete alone -- which is not the same as none of them being enough. spark
// sees stacks but not engine phases. CapFrameX sees total frame time but not
// what was inside it. F3+L splits the frame by section, which is the bridge.
// Captured in one window against one clock they are complete for DIAGNOSIS,
// and diagnosis is what narrows seven leave-one-out runs down to two.
//
// WHAT IT STILL CANNOT DO. Correlation names suspects. It does not measure what
// a mod costs in frames -- for that a run has to happen with the mod and
// without it. The report says so at the bottom rather than letting a reader
// infer otherwise from a confident-looking table.
//
// TESTED vs UNTESTED. The spark and log parsers have been run against real
// artifacts. The CapFrameX and F3+L parsers have not -- no such capture existed
// on this machine when they were written. Every section states its own
// provenance, because a parser that has never seen real data is a hypothesis
// about a file format.
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

const argv = process.argv.slice(2)
const one = (n, d = '') => { const i = argv.indexOf(`--${n}`); return i >= 0 && argv[i + 1] ? argv[i + 1] : d }
const many = n => argv.reduce((a, v, i) => (v === `--${n}` && argv[i + 1] ? [...a, argv[i + 1]] : a), [])

const out = []
// Carried from the frames section to the verdict. It was on globalThis, which
// hid the dependency between two sections that must agree or the verdict is
// wrong; a plain binding makes the coupling visible where it is declared.
let gpuBusy
const say = l => { out.push(l); console.log(l) }
const sum = a => (a || []).reduce((x, y) => x + y, 0)

if (!argv.length) {
  console.error('usage: session-report.mjs --log <latest.log> [--spark <code|json>]... [--capframex <csv>] [--profiler <txt>] [--expect-gpu <s>] [--out <md>]')
  process.exit(1)
}

say('# Session report\n')
say('> Generated by `scripts/analyze/session-report.mjs`. Every section states where its numbers')
say('> come from and whether that parser has been verified against real data.\n')

// ---------------------------------------------------------------- identity
const logPath = one('log')
let gpuOk = null
say('## Identity — from `latest.log`  ·  *parser verified*\n')
if (!logPath || !existsSync(logPath)) {
  say('**No log given.** Identity is unknown, and `PERF-HARNESS-IDENTITY` calls a run missing identity')
  say('fields not comparable. Everything below is a fragment.\n')
} else {
  const log = readFileSync(logPath, 'utf8')
  // These logs are CRLF. .trim() alone leaves a carriage return inside a
  // captured line, which breaks the markdown table cell it lands in -- the
  // first report generated did exactly that. Collapse any break, then trim.
  const clean = v => String(v || '').replace(/[\r\n]+/g, ' ').trim()
  const find = re => clean((log.match(re) || [, ''])[1])
  const gpu = find(/OpenGL Renderer:\s*(.+)/)
  // THE LAST one, not the first. A session where the shader pack was switched
  // writes several of these -- the log read while building this had six -- and
  // log.match() returns the first, which reported a pack that had been replaced
  // twenty minutes earlier.
  const shaderLines = [...log.matchAll(/Using shaderpack:\s*([^\r\n]+)/g)].map(m => clean(m[1]))
  const shader = shaderLines.length ? shaderLines[shaderLines.length - 1] : ''
  const mods = find(/Loading (\d+) mods/)
  const fw = clean([...log.matchAll(/Flywheel [Bb]ackend[^\r\n]*/g)].map(m => m[0]).slice(-1)[0])
  // Also the LAST, and for the same reason: Colorwheel complains once per pack
  // load, so the first complaint names a pack that may no longer be active.
  const cwAll = [...log.matchAll(/\[Colorwheel\][^\r\n]*/g)].map(m => clean(m[0]))
  const cw = cwAll.length ? cwAll[cwAll.length - 1] : ''
  const expect = one('expect-gpu')

  say(`| Field | Value |`)
  say(`|---|---|`)
  say(`| GPU | \`${gpu || 'not found'}\` |`)
  // oculus.properties is the authority on whether shaders are ON; the log only
  // says which pack was last LOADED, and a pack can be loaded and then disabled.
  let shaderState = ''
  // --shader-config, or nothing. This used to derive the path by rewriting the
  // log path -- and run-session passes a COPY of the log, so the pattern never
  // matched, .replace() returned the path unchanged, that file existed (it was
  // the log), and the log got parsed as a properties file. Result: every real
  // run reported "Shaders: OFF", including the ones with shaders on. Path
  // surgery on an unrelated path is a guess dressed as a lookup.
  const oculusCfg = one('shader-config')
  if (oculusCfg && !existsSync(oculusCfg)) {
    say(`| Shaders | **unknown** — \`${oculusCfg}\` not found |`)
  } else if (!oculusCfg) {
    say('| Shaders | **unknown** — no `--shader-config` given, so the on/off state is not established |')
  }
  if (oculusCfg && existsSync(oculusCfg)) {
    const cfg = readFileSync(oculusCfg, 'utf8')
    const on = /^enableShaders\s*=\s*true/mi.test(cfg)
    const pk = clean((cfg.match(/^shaderPack\s*=\s*(.+)$/mi) || [, ''])[1])
    shaderState = on ? `ON — \`${pk}\`` : 'OFF'
    say(`| Shaders | **${shaderState}** — from \`config/oculus.properties\` |`)
  }
  say(`| Shader pack last loaded | \`${shader || 'none'}\`${shaderLines.length > 1 ? ` (${shaderLines.length} loads this session)` : ''} |`)
  say(`| Mods loaded | ${mods || '?'} (includes JarJar libraries) |`)
  say(`| Flywheel | \`${fw.replace(/^.*?\]:\s*/, '') || 'no line — not a Create client, or never rendered'}\` |`)
  if (cw) say(`| Colorwheel | \`${cw.replace(/^.*?\[Colorwheel\]\s*/, '')}\` |`)
  say('')
  if (expect) {
    gpuOk = gpu.includes(expect)
    say(gpuOk
      ? `**GPU matches \`${expect}\`.**\n`
      : `**WRONG GPU — expected \`${expect}\`.** \`C-UPFG-07\` was exactly this. Everything below was\n` +
        `measured on hardware nobody meant to test; treat the whole report as void.\n`)
  }
  if (/flywheel:off/.test(fw)) {
    say('**Flywheel is off**, so Create machinery is drawing on the vanilla path (`C10`). If a shader')
    say('pack is loaded above, `C12` is the likely reason and the fix is a supported pack, not a mod.\n')
  }
}

// ---------------------------------------------------------------- frames
const cfx = one('capframex')
say('## Frames — from CapFrameX / PresentMon  ·  ⚠️ *parser NOT yet verified against a real capture*\n')
if (!cfx || !existsSync(cfx)) {
  say('**No capture given.** Without it there is no FPS, no 1% low and no GPU-busy figure — which')
  say('means the CPU-bound / GPU-bound verdict below cannot be reached, only guessed at.\n')
} else {
  const rows = readFileSync(cfx, 'utf8').split(/\r?\n/).filter(Boolean)
  const head = rows[0].split(/[,;]/).map(h => h.trim().toLowerCase())
  const col = (...names) => head.findIndex(h => names.some(n => h.includes(n)))
  const iFt = col('msbetweenpresents', 'frametime', 'frame time')
  const iGpu = col('gpubusy', 'msgpuactive', 'gpu busy')
  if (iFt < 0) {
    say(`**Could not find a frametime column.** Header was:\n\n\`\`\`\n${rows[0].slice(0, 300)}\n\`\`\`\n`)
    say('That is this parser being unverified, not the capture being wrong. Send the header and it')
    say('takes one line to teach it.\n')
  } else {
    const ft = rows.slice(1).map(r => parseFloat(r.split(/[,;]/)[iFt])).filter(n => Number.isFinite(n) && n > 0)
    const gpuB = iGpu >= 0 ? rows.slice(1).map(r => parseFloat(r.split(/[,;]/)[iGpu])).filter(Number.isFinite) : []
    const s = [...ft].sort((a, b) => a - b)
    const pct = p => s[Math.min(s.length - 1, Math.floor(s.length * p))]
    const avgFt = ft.reduce((a, b) => a + b, 0) / ft.length
    // 1% low, the usual definition: mean of the slowest 1% of frames
    const worst = s.slice(Math.floor(s.length * 0.99))
    const low1 = 1000 / (worst.reduce((a, b) => a + b, 0) / worst.length)
    say(`| Metric | Value |`)
    say(`|---|---|`)
    say(`| Frames | ${ft.length} |`)
    say(`| Avg FPS | ${(1000 / avgFt).toFixed(1)} |`)
    say(`| 1% low | ${low1.toFixed(1)} FPS |`)
    say(`| Frametime median | ${pct(0.5).toFixed(2)} ms |`)
    say(`| Frametime P95 | ${pct(0.95).toFixed(2)} ms |`)
    say(`| Frametime P99 | ${pct(0.99).toFixed(2)} ms |`)
    if (gpuB.length) {
      const g = gpuB.reduce((a, b) => a + b, 0) / gpuB.length
      // UNITS, AND THIS IS NOT GUESSABLE FROM THE VALUE. PresentMon v2 reports
      // GPUBusy in MILLISECONDS per frame; a fraction would be 0..1. The old
      // heuristic "<= 1.5 means a fraction" misreads a genuinely fast frame:
      // 1.2 ms of GPU work at 800 FPS is ms, not a fraction, and would have been
      // reported as 120% busy. Decide from the COLUMN NAME instead, and say so.
      const gpuIsMs = /ms/.test(head[iGpu]) || /busy/.test(head[iGpu])
      const gpuPct = gpuIsMs ? (g / avgFt) * 100 : g * 100
      const gpuNote = gpuIsMs ? `${g.toFixed(2)} ms of ${avgFt.toFixed(2)} ms` : 'reported as a fraction'
      say(`| GPU busy | ${gpuPct.toFixed(0)}% of frame time (${gpuNote}, column \`${head[iGpu]}\`) |`)
      gpuBusy = gpuPct
    }
    say('')
  }
}

// ---------------------------------------------------------------- cpu
const sparks = many('spark')
say('## CPU attribution — from spark  ·  *parser verified, reconstructs 100% on a known profile*\n')
const threadShare = {}
if (!sparks.length) {
  say('**No profile given.** Nothing here can name a mod.\n')
}
for (const src of sparks) {
  let d
  try {
    d = existsSync(src) ? JSON.parse(readFileSync(src, 'utf8'))
      : await (await fetch(`https://spark.lucko.me/${src}?raw=1&full=true`)).json()
  } catch (e) {
    say(`**Could not read \`${src}\`:** ${e.message}\n`); continue
  }
  if (d.type !== 'sampler') { say(`\`${src}\` is a "${d.type}" export, not a profile.\n`); continue }
  const cs = d.classSources || {}
  const names = (d.threads || []).map(t => t.name)
  say(`### \`${src}\` — threads sampled: ${names.map(n => `\`${n}\``).join(', ')}\n`)
  if (names.length === 1 && names[0] === 'Server thread') {
    say('**Only the server thread was sampled.** This profile cannot see a render-thread cost, and')
    say('the FPS question is a render-thread question (`C13`). Re-run with `--thread *`.\n')
  }
  for (const t of d.threads || []) {
    const pool = t.children || [], total = sum(t.times)
    if (!total) continue
    const byMod = new Map()
    for (const n of pool) {
      const self = sum(n.times) - (n.childrenRefs || []).reduce((a, i) => a + sum(pool[i]?.times), 0)
      if (self <= 0) continue
      const cls = n.className || '?'
      const mod = cs[cls] || (/^(net\.minecraft|com\.mojang|java\.|jdk\.|sun\.)/.test(cls) ? 'minecraft/jvm' : 'unattributed')
      byMod.set(mod, (byMod.get(mod) || 0) + self)
    }
    const rows = [...byMod.entries()].sort((a, b) => b[1] - a[1])
    const recon = (rows.reduce((a, r) => a + r[1], 0) / total) * 100
    const engine = (byMod.get('minecraft/jvm') || 0) / total
    threadShare[t.name] = { total, rows, engine }
    say(`**${t.name}** — ${total} samples, self-time reconstructs ${recon.toFixed(1)}%` +
        (Math.abs(recon - 100) > 2 ? ' ← **PARSE IS WRONG**' : '') + '\n')
    say('| Share | Mod |')
    say('|---|---|')
    for (const [m, v] of rows.slice(0, 12)) say(`| ${((v / total) * 100).toFixed(2)}% | ${m} |`)
    const rest = rows.slice(12).reduce((a, r) => a + r[1], 0)
    if (rest) say(`| ${((rest / total) * 100).toFixed(2)}% | *(${rows.length - 12} more)* |`)
    say('')
  }
  const st = Object.values(d.timeWindowStatistics || {})
  if (st.length) {
    const avg = k => st.reduce((a, x) => a + (x[k] ?? 0), 0) / st.length
    say(`TPS ${avg('tps').toFixed(2)} · MSPT median ${avg('msptMedian').toFixed(1)} ms · max ${Math.max(...st.map(x => x.msptMax ?? 0)).toFixed(0)} ms · ` +
        `entities ${Math.round(avg('entities'))} · chunks ${Math.round(avg('chunks'))}\n`)
  }
}

// ---------------------------------------------------------------- sections
const prof = one('profiler')
say('## Engine sections — from Minecraft F3+L  ·  ⚠️ *parser NOT yet verified against a real capture*\n')
if (!prof || !existsSync(prof)) {
  say('**Not given.** This is the one source that splits a frame by engine phase — render vs')
  say('entities vs particles vs gui — and it is the bridge between a frametime spike and a stack.')
  say('Without it, a spike can be located in time but not attributed to a phase.\n')
} else {
  const txt = readFileSync(prof, 'utf8')
  const lines = txt.split(/\r?\n/).filter(l => /\d+(\.\d+)?%/.test(l)).slice(0, 40)
  if (!lines.length) {
    say(`**No percentage lines found in \`${prof}\`.** Parser unverified — send the file and it is`)
    say('one line to teach it.\n')
  } else {
    say('```')
    lines.forEach(l => say(l.slice(0, 120)))
    say('```\n')
  }
}

// ---------------------------------------------------------------- verdict
say('## Bound verdict — the reason for correlating at all\n')
const render = threadShare['Render thread']
// gpuBusy is set above if, and only if, a GPU-busy column was parsed.
if (!render || gpuBusy === undefined) {
  const missing = []
  if (!render) missing.push('a spark profile that sampled the **Render thread** (`--thread *`)')
  if (gpuBusy === undefined) missing.push('a CapFrameX capture with a **GPU busy** column')
  say(`**Cannot be reached.** It needs ${missing.join(' and ')}.\n`)
  say('This is the whole point of capturing them together: neither one alone decides whether the')
  say('client is CPU-bound or GPU-bound, and every later decision hangs on that answer.\n')
} else {
  const modShare = 100 - render.engine * 100
  if (gpuBusy < 70) {
    say(`**CPU-bound on the render thread.** GPU busy ${gpuBusy.toFixed(0)}% — the card is idle while`)
    say('frames are slow, so the limit is the render thread, and the mod table for that thread above')
    say(`is the suspect list. Mods own ${modShare.toFixed(0)}% of it; the rest is Minecraft itself.\n`)
    say('**Next:** leave-one-out on the top two or three of that table only. Not all seven.\n')
  } else {
    say(`**GPU-bound.** GPU busy ${gpuBusy.toFixed(0)}%. The mod tables are not the lever — the shader`)
    say('preset and resolution are. Leave-one-out on optimisation mods would measure noise.\n')
  }
}

say('---\n')
say('**What this report cannot say.** Correlation names suspects; it does not measure what a mod')
say('costs in frames. That needs a run with the mod and a run without it')
say('(`PERF-HARNESS-LEAVEONEOUT`). A share above is CPU time on a thread, not frames.\n')

const dest = one('out')
if (dest) {
  mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, out.join('\n') + '\n')
  console.log(`\n→ written to ${dest}`)
}
